MVIT:
  CLS_EMBED_ON: true
  DROPPATH_RATE: 0.2
  DEPTH: 16
  DIM_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  HEAD_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  PATCH_KERNEL: [3, 7, 7]
  PATCH_PADDING: [1, 3, 3]
  PATCH_STRIDE: [2, 4, 4]
  POOL_KVQ_KERNEL: [3, 3, 3]
  POOL_Q_STRIDE: [[0, 1, 1, 1], [1, 1, 2, 2], [2, 1, 1, 1], [3, 1, 2, 2], [4, 1, 1, 1], [5, 1, 1, 1], [6, 1, 1, 1], [7, 1, 1, 1], [8, 1, 1, 1], [9, 1, 1, 1], [10, 1, 1, 1], [11, 1, 1, 1], [12, 1, 1, 1], [13, 1, 1, 1], [14, 1, 2, 2], [15, 1, 1, 1]]
  POOL_KV_STRIDE: [[0, 1, 8, 8], [1, 1, 4, 4], [2, 1, 4, 4], [3, 1, 2, 2], [4, 1, 2, 2], [5, 1, 2, 2], [6, 1, 2, 2], [7, 1, 2, 2], [8, 1, 2, 2], [9, 1, 2, 2], [10, 1, 2, 2], [11, 1, 2, 2], [12, 1, 2, 2], [13, 1, 2, 2], [14, 1, 1, 1], [15, 1, 1, 1]]
  POOL_KV_STRIDE_ADAPTIVE: [1, 8, 8]
  REL_POS_SPATIAL_SEP: true
  REL_POS_TEMPORAL: true
VISUAL_NET:
  TYPE: MViT
  RESOLUTION: 224
  PATCH_SIZE: 32
  WIDTH: 512
  LAYERS: 12
  HEADS: 1
  OUTPUT_DIM: 512
  EXTRA_TOKEN: 
TEXT_NET:
  DIM: 512
  CONTEXT_LENGTH: 77
  VOCAB_SIZE: 49408
  WIDTH: 512
  HEADS: 8
  LAYERS: 12
# SOLVER:
#   BASE_LR_SCALE_NUM_SHARDS: True
#   LR_POLICY: cosine
#   WEIGHT_DECAY: 0.05
#   OPTIMIZING_METHOD: adamw
#   CLIP_GRAD_L2NORM: 1.0
#   BASE_LR: 5.0e-5
#   WARMUP_EPOCHS: 10.0
#   WARMUP_START_LR: 5.0e-5
#   MAX_EPOCH: 60
SOLVER:  # step lr
  BASE_LR_SCALE_NUM_SHARDS: True
  LR_POLICY: steps_with_relative_lrs
  LRS: [1.0]
  STEPS: [0]
  WEIGHT_DECAY: 0.05
  OPTIMIZING_METHOD: adamw
  CLIP_GRAD_L2NORM: 1.0
  BASE_LR: 5.0e-5
  WARMUP_EPOCHS: 10.0
  WARMUP_START_LR:  5.0e-5
  MAX_EPOCH: 60
TRAIN:
  DATASET: epic
  BATCH_SIZE: 24 # 32
  CHECKPOINT_FILE_PATH: "CLIP : checkpoint/MViTv2_S_16x4_k400_f302660347.pyth : checkpoint/CLIP_ViT-B16_textnet.pth"
  CHECKPOINT_EPOCH_RESET: true
  EVAL_PERIOD: 2
TEST:
  DATASET: epic
  BATCH_SIZE: 12 # 16
DATA:
  PATH_TO_DATA_DIR: /ssd/FAST_DATA/epic-kitchens
  NUM_FRAMES: 16
  FPS: 8
  INPUT_CHANNEL_NUM: [3, 3]
  NUM_EVAL_VIEWS: 5
MODEL:
  NUM_CLASSES: 512
  CLS_CLASSES: 97
  DROPOUT_RATE: 0.5
  HEAD_ACT: "none"
  MODEL_NAME: CLIP_clsloss
MIXUP:
  ENABLE: false
NUM_GPUS: 3
TASK: verb_CLIP_clsloss
TEMPERATURE: 0.07
LOSS_TYPE: local
