MVIT:
  CLS_EMBED_ON: true   
  DROPPATH_RATE: 0.2
  DEPTH: 16
  DIM_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  HEAD_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  PATCH_KERNEL: [3, 7, 7]
  PATCH_PADDING: [1, 3, 3]
  PATCH_STRIDE: [2, 4, 4]
  POOL_KVQ_KERNEL: [3, 3, 3]
  POOL_Q_STRIDE: [[0, 1, 1, 1], [1, 1, 2, 2], [2, 1, 1, 1], [3, 1, 2, 2], [4, 1, 1, 1], [5, 1, 1, 1], [6, 1, 1, 1], [7, 1, 1, 1], [8, 1, 1, 1], [9, 1, 1, 1], [10, 1, 1, 1], [11, 1, 1, 1], [12, 1, 1, 1], [13, 1, 1, 1], [14, 1, 2, 2], [15, 1, 1, 1]]
  POOL_KV_STRIDE: [[0, 1, 8, 8], [1, 1, 4, 4], [2, 1, 4, 4], [3, 1, 2, 2], [4, 1, 2, 2], [5, 1, 2, 2], [6, 1, 2, 2], [7, 1, 2, 2], [8, 1, 2, 2], [9, 1, 2, 2], [10, 1, 2, 2], [11, 1, 2, 2], [12, 1, 2, 2], [13, 1, 2, 2], [14, 1, 1, 1], [15, 1, 1, 1]]
  POOL_KV_STRIDE_ADAPTIVE: [1, 8, 8]
  REL_POS_SPATIAL_SEP: true
  REL_POS_TEMPORAL: true
TEXT_NET:
  DIM: 512
  CONTEXT_LENGTH: 77
  VOCAB_SIZE: 49408
  WIDTH: 512
  HEADS: 8
  LAYERS: 12
VISUAL_NET:
  type: ViT
  dim: 512
  resolution: 224
  patch_size: 16
  width: 768
  heads: 12
  layers: 12
  extra_token: 1
  aggregation: "none"
  aggregation_reduce: True
  aggregation_layers: 6
SOLVER:  # step lr
  BASE_LR_SCALE_NUM_SHARDS: True
  WEIGHT_DECAY: 0.05
  OPTIMIZING_METHOD: adamw
  CLIP_GRAD_L2NORM: 1.0

  LR_POLICY: cosine
  BASE_LR: 5.0e-5
  WARMUP_EPOCHS: 5.0
  WARMUP_START_LR:  2.5e-5
  MAX_EPOCH: 61
TRAIN:
  ENABLE: False
  DATASET: One4AllDataset_Attr
  EXTRA_MASK: "train:/home/user/lmy/DATA/independent_attr1/train_code/abcd/video_property/One4all_train_10K_sc5.json; val:/home/user/lmy/DATA/independent_attr1/train_code/abcd/video_property/One4all_train_10K_sc5.json"
  BATCH_SIZE: 32
  CHECKPOINT_FILE_PATH: "/home/user/lmy/DATA/independent_attr1/train_code/abcd/checkpoint/CLIP_ViT-B16.pth"
  # CHECKPOINT_FILE_PATH: "/home/user/lmy/DATA/independent_attr1/train_code/abcd/logs/123/checkpoints/checkpoint_epoch_00061.pyth"
  CHECKPOINT_EPOCH_RESET: true
  EVAL_PERIOD: 5
TEST:
  ENABLE: True
  DATASET: CGQA
  BATCH_SIZE: 32
DATA:
  PATH_TO_DATA_DIR: "."
  NUM_FRAMES: 1
  FPS: 8
  INPUT_CHANNEL_NUM: [3, 3]
  NUM_EVAL_VIEWS: 5
MODEL:
  NUM_CLASSES: 512
  DROPOUT_RATE: 0.5
  HEAD_ACT: "none"
  MODEL_NAME: CLIPimg
MIXUP:
  ENABLE: false
NUM_GPUS: 1
TASK: verb_CLIP
TEMPERATURE: 0.07
LOSS_TYPE: local
